import type { PlanItem as Item } from '../types';
export type Project = {
  name: string;
  floors: Item[][];
};
export const room = (
  id: string,
  name: string,
  x: number,
  y: number,
  w: number,
  h: number,
  color = '#e9eef4',
): Item => ({ id, kind: 'room', name, x, y, w, h, rotation: 0, color });
export const obj = (
  kind: Item['kind'],
  name: string,
  x: number,
  y: number,
  w: number,
  h: number,
): Item => ({
  ...room(crypto.randomUUID(), name, x, y, w, h),
  kind,
  color: '#ffffff',
});
export const seed: Project = {
  name: 'Мой семейный дом',
  floors: [
    [
      room('a', 'Кухня-гостиная', 3, 3, 6, 5, '#edf0e8'),
      room('b', 'Спальня', 9, 3, 4, 4, '#e8edf4'),
      room('c', 'Ванная', 9, 7, 2.5, 2.5, '#e5f0f2'),
      room('d', 'Туалет', 11.5, 7, 1.5, 2.5, '#e5f0f2'),
      room('e', 'Прихожая', 3, 8, 3, 3.5, '#f3eee7'),
      room('f', 'Лестница / холл', 6, 8, 3, 3.5, '#eeedf3'),
      room('g', 'Котельная', 9, 9.5, 2, 2.5, '#eeeeee'),
      room('h', 'Гардеробная', 11, 9.5, 2, 2.5, '#f3eee7'),
      {
        id: 'sofa',
        kind: 'sofa',
        name: 'Диван',
        x: 3.7,
        y: 3.7,
        w: 2.6,
        h: 1,
        rotation: 0,
        color: '#ffffff',
      },
      {
        id: 'bed',
        kind: 'bed',
        name: 'Кровать',
        x: 10,
        y: 3.5,
        w: 1.8,
        h: 2,
        rotation: 0,
        color: '#ffffff',
      },
      {
        id: 'kitchen',
        kind: 'kitchen',
        name: 'Кухня',
        x: 3.3,
        y: 6.9,
        w: 3.5,
        h: 0.65,
        rotation: 0,
        color: '#ffffff',
      },
      {
        id: 'stairs',
        kind: 'stairs',
        name: 'Лестница',
        x: 6.3,
        y: 8.4,
        w: 1,
        h: 2.5,
        rotation: 0,
        color: '#ffffff',
      },
      {
        id: 'door',
        kind: 'door',
        name: 'Дверь',
        x: 5,
        y: 8,
        w: 0.9,
        h: 0.9,
        rotation: 0,
        color: '#ffffff',
      },
      {
        id: 'window',
        kind: 'window',
        name: 'Окно',
        x: 5,
        y: 3,
        w: 1.8,
        h: 0.12,
        rotation: 0,
        color: '#ffffff',
      },
    ],
    [
      room('i', 'Спальня родителей', 3, 3, 5, 4, '#e8edf4'),
      room('j', 'Детская', 8, 3, 3, 4, '#f4ede4'),
      room('k', 'Детская', 11, 3, 3, 4, '#e8efeb'),
      room('l', 'Кабинет', 3, 7, 3, 3, '#edf0e8'),
      room('m', 'Холл', 6, 7, 3, 4.5, '#eeedf3'),
      room('n', 'Ванная', 9, 7, 2.5, 2.5, '#e5f0f2'),
      room('o', 'Туалет', 11.5, 7, 1.5, 2.5, '#e5f0f2'),
    ],
  ],
};
