"use client";
import { useEffect, useRef, useState } from 'react';
import { MousePointer2, Square, Minus, DoorOpen, PanelsTopLeft, BedDouble, Sofa, CookingPot, Bath, MoveUpRight, Plus, Undo2, Redo2, Download, Upload, Trash2, Copy, RotateCw, Layers, House, ZoomIn, ZoomOut, Grid2X2, FilePlus2, Check, X } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
type Item={id:string;kind:string;name:string;x:number;y:number;w:number;h:number;rotation:number;color:string};
type Project={name:string;floors:Item[][]};
const room=(id:string,name:string,x:number,y:number,w:number,h:number,color='#e9eef4'):Item=>({id,kind:'room',name,x,y,w,h,rotation:0,color});
const obj=(kind:string,name:string,x:number,y:number,w:number,h:number):Item=>({...room(crypto.randomUUID(),name,x,y,w,h),kind,color:'#ffffff'});
const seed:Project={name:'Мой семейный дом',floors:[[
room('a','Кухня-гостиная',3,3,6,5,'#edf0e8'),room('b','Спальня',9,3,4,4,'#e8edf4'),room('c','Ванная',9,7,2.5,2.5,'#e5f0f2'),room('d','Туалет',11.5,7,1.5,2.5,'#e5f0f2'),room('e','Прихожая',3,8,3,3.5,'#f3eee7'),room('f','Лестница / холл',6,8,3,3.5,'#eeedf3'),room('g','Котельная',9,9.5,2,2.5,'#eeeeee'),room('h','Гардеробная',11,9.5,2,2.5,'#f3eee7'),
{id:'sofa',kind:'sofa',name:'Диван',x:3.7,y:3.7,w:2.6,h:1,rotation:0,color:'#fff'}, {id:'bed',kind:'bed',name:'Кровать',x:10,y:3.5,w:1.8,h:2,rotation:0,color:'#fff'}, {id:'kitchen',kind:'kitchen',name:'Кухня',x:3.3,y:6.9,w:3.5,h:.65,rotation:0,color:'#fff'}, {id:'stairs',kind:'stairs',name:'Лестница',x:6.3,y:8.4,w:1,h:2.5,rotation:0,color:'#fff'}, {id:'door',kind:'door',name:'Дверь',x:5,y:8,w:.9,h:.9,rotation:0,color:'#fff'}, {id:'window',kind:'window',name:'Окно',x:5,y:3,w:1.8,h:.12,rotation:0,color:'#fff'}
],[room('i','Спальня родителей',3,3,5,4,'#e8edf4'),room('j','Детская',8,3,3,4,'#f4ede4'),room('k','Детская',11,3,3,4,'#e8efeb'),room('l','Кабинет',3,7,3,3,'#edf0e8'),room('m','Холл',6,7,3,4.5,'#eeedf3'),room('n','Ванная',9,7,2.5,2.5,'#e5f0f2'),room('o','Туалет',11.5,7,1.5,2.5,'#e5f0f2')]]};
const tools=[{id:'select',label:'Выбрать',icon:MousePointer2},{id:'room',label:'Комната',icon:Square},{id:'wall',label:'Стена',icon:Minus},{id:'door',label:'Дверь',icon:DoorOpen},{id:'window',label:'Окно',icon:PanelsTopLeft}];
const furniture=[{id:'bed',label:'Кровать',icon:BedDouble,w:1.8,h:2},{id:'sofa',label:'Диван',icon:Sofa,w:2.4,h:.9},{id:'kitchen',label:'Кухня',icon:CookingPot,w:3,h:.6},{id:'bath',label:'Ванна',icon:Bath,w:.75,h:1.7},{id:'stairs',label:'Лестница',icon:MoveUpRight,w:1,h:3}];
const snap=(v:number)=>Math.round(v*10)/10;
function validProject(v:any):v is Project{return v&&typeof v.name==='string'&&Array.isArray(v.floors)&&v.floors.length>0&&v.floors.length<=8&&v.floors.every((f:any)=>Array.isArray(f)&&f.length<=500&&f.every((i:any)=>i&&typeof i.id==='string'&&typeof i.name==='string'&&['room','wall','door','window','bed','sofa','kitchen','bath','stairs'].includes(i.kind)&&['x','y','w','h','rotation'].every(k=>Number.isFinite(i[k]))&&i.w>0&&i.h>0&&i.x>=0&&i.y>=0&&i.x+i.w<=24&&i.y+i.h<=20&&/^#[a-fA-F0-9]{6}$/.test(i.color)))}
export default function Home(){
 const [project,setProject]=useState<Project>(seed),[floor,setFloor]=useState(0),[tool,setTool]=useState('select'),[selected,setSelected]=useState<string|null>(null),[zoom,setZoom]=useState(1),[grid,setGrid]=useState(true),[templates,setTemplates]=useState(false),[status,setStatus]=useState(''),[loaded,setLoaded]=useState(false),[past,setPast]=useState<Project[]>([]),[future,setFuture]=useState<Project[]>([]);
 const svg=useRef<SVGSVGElement>(null),file=useRef<HTMLInputElement>(null),gesture=useRef<any>(null),state=useRef(project);state.current=project;
 const items=project.floors[floor]||[],active=items.find(i=>i.id===selected),total=items.filter(i=>i.kind==='room').reduce((s,i)=>s+i.w*i.h,0);
 const commit=(p:Project)=>{setPast(h=>[...h.slice(-49),state.current]);setFuture([]);setProject(p)};
 const replaceItems=(list:Item[])=>({...state.current,floors:state.current.floors.map((f,n)=>n===floor?list:f)});
 const patch=(values:Partial<Item>)=>{if(!active)return;const next={...active,...values};next.w=Math.max(.1,Math.min(next.w,24-next.x));next.h=Math.max(.1,Math.min(next.h,20-next.y));commit(replaceItems(items.map(i=>i.id===selected?next:i)))};
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('domplan-project')||'null');if(validProject(p))setProject(p)}catch{}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('domplan-project',JSON.stringify(project))}catch{setStatus('Память браузера недоступна. Скачайте проект.')}},[project,loaded]);
 useEffect(()=>{if(!status)return;const t=setTimeout(()=>setStatus(''),3500);return()=>clearTimeout(t)},[status]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:'read_house_plan',description:'Read current house plan and all floors.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>state.current},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
 const undo=()=>{if(!past.length)return;setFuture(h=>[state.current,...h]);setProject(past[past.length-1]);setPast(h=>h.slice(0,-1));setSelected(null)};
 const redo=()=>{if(!future.length)return;setPast(h=>[...h,state.current]);setProject(future[0]);setFuture(h=>h.slice(1));setSelected(null)};
 const remove=()=>{commit(replaceItems(items.filter(i=>i.id!==selected)));setSelected(null)};
 const point=(e:React.PointerEvent)=>{const p=svg.current!.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.current!.getScreenCTM()!.inverse());return{x:snap(Math.max(0,Math.min(24,q.x))),y:snap(Math.max(0,Math.min(20,q.y)))}};
 const down=(e:React.PointerEvent,id?:string)=>{if(e.button!==0)return;const p=point(e);svg.current!.setPointerCapture(e.pointerId);if(tool==='select'){setSelected(id||null);if(id){const i=items.find(i=>i.id===id)!;gesture.current={mode:'move',p,item:i,original:state.current}}return}const newid=crypto.randomUUID();const name=tool==='room'?'Новая комната':tools.find(t=>t.id===tool)?.label||furniture.find(f=>f.id===tool)?.label||'Объект';let w=1,h=1;const f=furniture.find(f=>f.id===tool);if(f){w=f.w;h=f.h}if(tool==='window'){w=1.5;h=.12}if(tool==='wall'){w=.2;h=.2}if(tool==='door'){w=.9;h=.9}const i={...obj(tool,name,Math.min(p.x,24-w),Math.min(p.y,20-h),w,h),id:newid};gesture.current={mode:['room','wall'].includes(tool)?'draw':'place',p,item:i,original:state.current};setSelected(newid);setProject(replaceItems([...items,i]))};
 const move=(e:React.PointerEvent)=>{const g=gesture.current;if(!g)return;const p=point(e);let i=g.item;if(g.mode==='move')i={...i,x:Math.max(0,Math.min(24-i.w,snap(i.x+p.x-g.p.x))),y:Math.max(0,Math.min(20-i.h,snap(i.y+p.y-g.p.y)))};if(g.mode==='draw'){if(tool==='wall'){const horizontal=Math.abs(p.x-g.p.x)>=Math.abs(p.y-g.p.y);i={...i,x:Math.min(g.p.x,p.x),y:Math.min(g.p.y,p.y),w:horizontal?Math.max(.2,Math.abs(p.x-g.p.x)):.2,h:horizontal?.2:Math.max(.2,Math.abs(p.y-g.p.y))}}else i={...i,x:Math.min(p.x,g.p.x),y:Math.min(p.y,g.p.y),w:Math.max(.2,Math.abs(p.x-g.p.x)),h:Math.max(.2,Math.abs(p.y-g.p.y))};}i={...i,x:Math.min(i.x,24-i.w),y:Math.min(i.y,20-i.h)};setProject(replaceItems(state.current.floors[floor].map(o=>o.id===i.id?i:o)))};
 const up=()=>{if(!gesture.current)return;const g=gesture.current;setPast(h=>[...h.slice(-49),g.original]);setFuture([]);gesture.current=null;if(g.mode!=='move')setTool('select')};
 const download=(data:string,name:string,type:string)=>{const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const exportSvg=()=>{const copy=svg.current!.cloneNode(true) as SVGSVGElement;copy.setAttribute('xmlns','http://www.w3.org/2000/svg');copy.setAttribute('width','1200');copy.setAttribute('height','1000');copy.querySelectorAll('[data-selection]').forEach(n=>n.remove());download(new XMLSerializer().serializeToString(copy),`план-этаж-${floor+1}.svg`,'image/svg+xml');setStatus('Схема этажа скачана')};
 const loadTemplate=(kind:string)=>{let p:Project=JSON.parse(JSON.stringify(seed));if(kind==='empty')p={name:'Новый проект',floors:[[]]};if(kind==='single')p={name:'Одноэтажный дом',floors:[[room('s1','Кухня-гостиная',3,3,6,5,'#edf0e8'),room('s2','Спальня',9,3,4,4,'#e8edf4'),room('s3','Детская',3,8,3,4,'#f3eee7'),room('s4','Детская',6,8,3,4,'#e8efeb'),room('s5','Холл',9,7,4,2),room('s6','Ванная',9,9,2.5,3,'#e5f0f2'),room('s7','Туалет',11.5,9,1.5,3,'#e5f0f2')]]};commit(p);setFloor(0);setSelected(null);setTemplates(false);setStatus('Проект открыт. Предыдущий план можно вернуть через отмену.')};
 return <div className="app"><header className="header"><a className="brand" href="/" aria-label="ДомПлан"><span className="brand-icon"><House size={22}/></span>дом<span className="brand-light">план</span><small>STUDIO</small></a><div className="project-title"><input aria-label="Название проекта" value={project.name} onChange={e=>setProject({...project,name:e.target.value})}/><span><Check size={13}/> В этом браузере</span></div><div className="header-actions"><button className="quiet" onClick={()=>setTemplates(true)}><FilePlus2 size={17}/> Новый проект</button><button className="primary" onClick={()=>{download(JSON.stringify(project,null,2),'дом-проект.json','application/json');setStatus('Файл проекта скачан')}}><Download size={17}/> Сохранить проект</button></div></header>
 <div className="workspace"><aside className="left-panel"><div className="panel-heading">СОЗДАТЬ ПЛАН</div><div className="tool-list">{tools.map(t=><button key={t.id} className={tool===t.id?'tool active':'tool'} onClick={()=>setTool(t.id)}><t.icon size={19}/><span>{t.label}</span>{tool===t.id&&<span className="tool-dot"/>}</button>)}</div><div className="panel-heading section-gap">МЕБЕЛЬ И ОБЪЕКТЫ</div><div className="furniture">{furniture.map(f=><button key={f.id} className={tool===f.id?'furn active':'furn'} onClick={()=>setTool(f.id)}><f.icon size={25}/><span>{f.label}</span></button>)}</div><div className="left-bottom"><button className="template-btn" onClick={()=>setTemplates(true)}><Layers size={19}/><div>Готовые планировки<small>Начните с шаблона</small></div></button><p>Комнату и стену рисуйте протягиванием. Объекты ставьте нажатием.</p></div></aside>
 <main className="editor"><div className="canvas-toolbar"><Tabs value={String(floor)} onValueChange={v=>{setFloor(Number(v));setSelected(null)}}><TabsList className="floor-tabs">{project.floors.map((_,n)=><TabsTrigger key={n} value={String(n)}>{n+1} этаж</TabsTrigger>)}</TabsList></Tabs><button title="Добавить этаж" aria-label="Добавить этаж" className="icon-btn" disabled={project.floors.length>=8} onClick={()=>{commit({...project,floors:[...project.floors,[]]});setFloor(project.floors.length);setSelected(null)}}><Plus size={18}/></button><span className="toolbar-separator"/><button className="icon-btn" title="Отменить" aria-label="Отменить" disabled={!past.length} onClick={undo}><Undo2 size={18}/></button><button className="icon-btn" title="Повторить" aria-label="Повторить" disabled={!future.length} onClick={redo}><Redo2 size={18}/></button><div className="toolbar-end"><Checkbox id="grid" checked={grid} onCheckedChange={v=>setGrid(v===true)}/><label htmlFor="grid">Сетка</label><button className="quiet export" onClick={exportSvg}><Download size={16}/> SVG</button></div></div>
 <div className="canvas-scroll"><div className="drawing-sheet" style={{width:`${100*zoom}%`,minWidth:650*zoom}}><div className="sheet-caption"><span>ПЛАН {floor+1} ЭТАЖА</span><span>Размеры в метрах</span></div><svg ref={svg} viewBox="0 0 24 20" className="plan" role="img" aria-label={`Редактор плана, этаж ${floor+1}`} onPointerDown={e=>down(e)} onPointerMove={move} onPointerUp={up} onPointerCancel={up} style={{cursor:tool==='select'?'default':'crosshair'}}><defs><pattern id="smallgrid" width=".1" height=".1" patternUnits="userSpaceOnUse"><path d="M .1 0 L 0 0 0 .1" fill="none" stroke="#e3e8ee" strokeWidth=".008"/></pattern><pattern id="grid" width="1" height="1" patternUnits="userSpaceOnUse"><rect width="1" height="1" fill="url(#smallgrid)"/><path d="M 1 0 L 0 0 0 1" fill="none" stroke="#cad3df" strokeWidth=".012"/></pattern></defs><rect width="24" height="20" fill="#ffffff"/>{grid&&<rect width="24" height="20" fill="url(#grid)"/>}{Array.from({length:23},(_,n)=><text key={n} x={n+1} y=".55" fontSize=".2" fill="#97a5b4" textAnchor="middle" className="ruler">{n+1}</text>)}{Array.from({length:19},(_,n)=><text key={n} x=".35" y={n+1} fontSize=".2" fill="#97a5b4" textAnchor="middle" className="ruler">{n+1}</text>)}
 {[...items.filter(i=>i.kind==='room'),...items.filter(i=>i.kind!=='room')].map(i=><g key={i.id} onPointerDown={e=>{e.stopPropagation();down(e,i.id)}} transform={`translate(${i.x} ${i.y})`}>
 <g transform={`rotate(${i.rotation} ${i.w/2} ${i.h/2})`}>
 {i.kind==='room'?<><rect width={i.w} height={i.h} fill={i.color} stroke="#35414e" strokeWidth=".13"/><text x={i.w/2} y={i.h/2-.1} textAnchor="middle" fontSize={Math.min(.32,i.w*.1)} fill="#243343" fontWeight="550">{i.name}</text><text x={i.w/2} y={i.h/2+.36} textAnchor="middle" fontSize=".26" fill="#788594">{(i.w*i.h).toFixed(1)} м²</text><text x={i.w/2} y={i.h-.25} textAnchor="middle" fontSize=".2" fill="#85919c">{i.w.toFixed(1)} × {i.h.toFixed(1)} м</text></>:i.kind==='wall'?<rect width={i.w} height={i.h} fill="#35414e"/>:i.kind==='door'?<><rect width={i.w} height=".18" y="-.09" fill="white"/><path d={`M 0 0 L 0 ${i.h} M 0 ${i.h} A ${i.w} ${i.h} 0 0 0 ${i.w} 0`} fill="none" stroke="#738396" strokeWidth=".035"/></>:i.kind==='window'?<><rect width={i.w} height={i.h} fill="white" stroke="#547e98" strokeWidth=".05"/><path d={`M 0 ${i.h/2} H ${i.w}`} stroke="#547e98" strokeWidth=".025"/></>:<><rect width={i.w} height={i.h} rx=".08" fill="#fcfcfd" stroke="#8f9cab" strokeWidth=".035"/>{i.kind==='bed'&&<><rect x=".1" y=".1" width={i.w/2-.15} height=".4" rx=".08" fill="#edf0f4" stroke="#a3adb9" strokeWidth=".02"/><rect x={i.w/2+.03} y=".1" width={i.w/2-.15} height=".4" rx=".08" fill="#edf0f4" stroke="#a3adb9" strokeWidth=".02"/><path d={`M .1 .65 H ${i.w-.1}`} stroke="#a3adb9" strokeWidth=".025"/></>}{i.kind==='sofa'&&<><rect x=".18" y=".2" width={i.w-.36} height={i.h-.32} rx=".08" fill="#e6e9ef"/><path d={`M ${i.w/2} .2 V ${i.h-.1}`} stroke="#a3adb9" strokeWidth=".025"/></>}{i.kind==='stairs'&&Array.from({length:12},(_,n)=><line key={n} x1="0" x2={i.w} y1={n*i.h/12} y2={n*i.h/12} stroke="#a3adb9" strokeWidth=".02"/>)}{i.kind==='bath'&&<rect x=".09" y=".1" width={i.w-.18} height={i.h-.2} rx=".25" fill="#edf4f6" stroke="#9ab3bd" strokeWidth=".025"/>}{i.kind==='kitchen'&&Array.from({length:Math.floor(i.w/.6)},(_,n)=><rect key={n} x={n*.6+.05} y=".07" width=".5" height={i.h-.14} fill="#edf0f4" stroke="#a3adb9" strokeWidth=".02"/>)}</>}
 </g>{i.id===selected&&<g data-selection="true"><rect x="-.1" y="-.1" width={i.w+.2} height={i.h+.2} fill="none" stroke="#db6545" strokeDasharray=".1 .07" strokeWidth=".04"/>{[[0,0],[i.w,0],[0,i.h],[i.w,i.h]].map(([x,y],n)=><rect key={n} x={x-.07} y={y-.07} width=".14" height=".14" fill="white" stroke="#db6545" strokeWidth=".035"/>)}</g>}</g>)}
 </svg></div></div><div className="canvas-footer"><span><span className="crosshair">⊹</span> Привязка 10 см <span className="footer-muted">· Поле 24 × 20 м</span></span><div className="zoom"><button aria-label="Уменьшить" onClick={()=>setZoom(z=>Math.max(.6,snap(z-.2)))}><ZoomOut size={17}/></button><button onClick={()=>setZoom(1)}>{Math.round(zoom*100)}%</button><button aria-label="Увеличить" onClick={()=>setZoom(z=>Math.min(2.4,snap(z+.2)))}><ZoomIn size={17}/></button></div></div></main>
 <aside className="right-panel"><div className="panel-heading">{active?'СВОЙСТВА ОБЪЕКТА':'ОБЗОР ПРОЕКТА'}</div>{active?<><div className="selection-title"><Square size={19}/><h2>{active.kind==='room'?'Комната':active.name}</h2><button aria-label="Снять выделение" className="icon-btn" onClick={()=>setSelected(null)}><X size={16}/></button></div><label className="field">Название<input value={active.name} onChange={e=>patch({name:e.target.value})}/></label><div className="field-grid">{([{key:'w',label:'Ширина'},{key:'h',label:'Длина'},{key:'x',label:'X'},{key:'y',label:'Y'}] as const).map(f=><label className="field" key={f.key}>{f.label}<div className="unit-input"><input type="number" min={f.key==='x'||f.key==='y'?0:.1} step=".1" max={f.key==='x'||f.key==='w'?24:20} value={active[f.key]} onChange={e=>{if(e.target.value==='')return;const v=Number(e.target.value);if(!Number.isFinite(v)||v<0)return;patch({[f.key]:Math.min(v,f.key==='x'?24-active.w:f.key==='y'?20-active.h:24)})}}/><span>м</span></div></label>)}</div>{active.kind==='room'&&<><div className="area-card"><span>Площадь комнаты</span><strong>{(active.w*active.h).toFixed(1)} <small>м²</small></strong></div><label className="field">Цвет комнаты<div className="swatches">{['#e9eef4','#edf0e8','#f3eee7','#e5f0f2','#eeedf3','#e8efeb'].map(c=><button key={c} style={{background:c}} aria-label={`Цвет ${c}`} className={active.color===c?'chosen':''} onClick={()=>patch({color:c})}/>)}</div></label></>}<div className="object-actions"><button onClick={()=>{const i={...active,id:crypto.randomUUID(),x:Math.min(24-active.w,active.x+.3),y:Math.min(20-active.h,active.y+.3)};commit(replaceItems([...items,i]));setSelected(i.id)}}><Copy size={16}/> Копия</button>{active.kind!=='room'&&active.kind!=='wall'&&<button onClick={()=>patch({rotation:(active.rotation+90)%360})}><RotateCw size={16}/> Повернуть</button>}<button className="danger" onClick={remove}><Trash2 size={16}/> Удалить</button></div></>:<><h2 className="overview-title">Ваш дом начинается<br/>с хорошего плана.</h2><p className="muted">Выберите комнату или объект на схеме, чтобы изменить его размеры.</p><div className="area-card"><span>Комнаты на этаже</span><strong>{total.toFixed(1)} <small>м²</small></strong></div><div className="stat-row"><span>Комнат</span><b>{items.filter(i=>i.kind==='room').length}</b></div><div className="stat-row"><span>Этажей</span><b>{project.floors.length}</b></div></>}
 <div className="room-section"><div className="panel-heading">КОМНАТЫ НА ЭТАЖЕ <span>{items.filter(i=>i.kind==='room').length}</span></div>{items.filter(i=>i.kind==='room').map(i=><button key={i.id} className={selected===i.id?'room-row selected':'room-row'} onClick={()=>{setSelected(i.id);setTool('select')}}><span className="room-color" style={{background:i.color}}/><span>{i.name}</span><small>{(i.w*i.h).toFixed(1)}</small></button>)}{!items.some(i=>i.kind==='room')&&<p className="muted">Выберите «Комната» и нарисуйте прямоугольник на сетке.</p>}</div><div className="right-bottom"><button className="quiet" onClick={()=>file.current?.click()}><Upload size={16}/> Открыть файл проекта</button><input type="file" accept=".json" ref={file} hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>2000000)throw Error();const p=JSON.parse(await f.text());if(!validProject(p))throw Error();commit(p);setFloor(0);setSelected(null);setStatus('Проект открыт')}catch{setStatus('Не удалось открыть файл. Нужен корректный проект ДомПлан.')}e.target.value=''}}/><p>Эскиз для планирования.<br/>Не заменяет строительный проект.</p></div></aside></div>
 {status&&<div className="toast" role="status"><Check size={17}/>{status}</div>}
 <Dialog open={templates} onOpenChange={setTemplates}><DialogContent className="templates-dialog"><DialogTitle className="dialog-heading">С чего начнём?</DialogTitle><DialogDescription>Откройте шаблон или создайте план с чистого листа. Текущий план можно вернуть кнопкой отмены.</DialogDescription><div className="template-cards">{[{id:'empty',name:'Чистый лист',desc:'Любые размеры и ваши идеи',rooms:[]},{id:'single',name:'Один этаж',desc:'Семейный дом · 7 комнат',rooms:[[0,0,60,50],[60,0,40,40],[0,50,30,50],[30,50,30,50],[60,40,40,20],[60,60,25,40],[85,60,15,40]]},{id:'family',name:'Два этажа',desc:'4 спальни · кабинет · 2 этажа',rooms:[[0,0,60,50],[60,0,40,40],[60,40,25,25],[85,40,15,25],[0,50,30,35],[30,50,30,35],[60,65,20,25],[80,65,20,25]]}].map(t=><button className="template-card" key={t.id} onClick={()=>loadTemplate(t.id)}><div className="template-preview">{t.id==='empty'?<Plus size={40}/>:<svg viewBox="-5 -5 110 110">{t.rooms.map(([x,y,w,h],n)=><rect key={n} x={x} y={y} width={w} height={h} fill={['#e8edf4','#edf0e8','#f3eee7'][n%3]} stroke="#455366" strokeWidth="2"/>)}</svg>}</div><b>{t.name}</b><span>{t.desc}</span></button>)}</div></DialogContent></Dialog>
 </div>;
}
